apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cqlsh
spec:
  selector:
    matchLabels:
      app: cqlsh
  template:
    metadata:
      labels:
        app: cqlsh
    spec:
      containers:
      - image: jsanda/cqlsh-k8s:b2b26a26344c
        name: cqlsh
